
site_name: 'Manual de Usuario de Spark'
theme:
  name: material
nav:
  - Home: index.md
  - Introducción: introduccion.md
  - Instalación: instalacion.md
  - Guía de Uso: guia-de-uso.md
  - FAQ: faq.md

